### ISSUE TITLE
error on windows 10 

### ISSUE THREAD

**Issue by djouallah** [googledatastudio/dscc-scripts#14]
on windows 10, when I run 
npm run update_message -- --format=object

i get this error, I am showing the whole log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'update_message',
1 verbose cli   '--',
1 verbose cli   '--format=object' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'preupdate_message', 'update_message', 'postupdate_message' ]
5 info lifecycle @~preupdate_message: @
6 info lifecycle @~update_message: @
7 verbose lifecycle @~update_message: unsafe-perm in lifecycle true
8 verbose lifecycle @~update_message: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\mimoune.djouallah\kepler\node_modules\.bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Common Files\Hitachi ID\;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Webex\Webex\Applications;C:\Program Files\nodejs\;C:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python37\;C:\Users\mimoune.djouallah\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2\bin;;C:\Users\mimoune.djouallah\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\mimoune.djouallah\AppData\Roaming\npm;C:\Users\mimoune.djouallah\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\nodejs;
9 verbose lifecycle @~update_message: CWD: C:\Users\mimoune.djouallah\kepler
10 silly lifecycle @~update_message: Args: [ '/d /s /c',
10 silly lifecycle   'dscc-scripts viz update_message -f object "--format=object"' ]
11 silly lifecycle @~update_message: Returned: code: 1  signal: null
12 info lifecycle @~update_message: Failed to exec update_message script
13 verbose stack Error: @ update_message: `dscc-scripts viz update_message -f object "--format=object"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @
15 verbose cwd C:\Users\mimoune.djouallah\kepler
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "update_message" "--" "--format=object"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ update_message: `dscc-scripts viz update_message -f object "--format=object"`
22 error Exit status 1
23 error Failed at the @ update_message script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by djouallah** [comment]
closed as windows is not supported
